name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # or the branch you are using

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .  # Set to the root or the correct directory
          destination: ./_site
          future: false
          verbose: true
